apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver1
  labels:
    app: wp-dep1
spec:
  selector:
    matchLabels:
      app: wp-dep1
  template:
    metadata:
      labels:
        app: wp-dep1
    spec:
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.containers.image }}
        env:
        - name: WORDPRESS_DB_HOST
          value: my-release-mysql.default.svc.cluster.local
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: secretpassword
        - name: WORDPRESS_DB_NAME
          value: app_database
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: 8000
