apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ingress1
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.annotations }}
   # nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    name: wp-ingress1
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts: 
      - {{ .Values.ingress.tls.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.ingress.rules.host }}
    http:
      paths:
      - pathType: {{ .Values.ingress.rules.http.paths.pathType }}
        path: {{ .Values.ingress.rules.http.paths.path }}
        backend:
          service:
            name: {{ .Values.ingress.rules.http.paths.backend.service.name }}
            port: 
              number: {{ .Values.ingress.rules.http.paths.backend.service.port.number }}

      