apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wordpress.name }}
  labels:
    app: {{ .Values.wordpress.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.wordpress.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.wordpress.name }}
    spec:
      containers:
      - name: {{ .Values.wordpress.name }}
        image: {{ .Values.wordpress.image }}
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
           secretKeyRef:
             name: {{ .Values.secret.name }}
             key: host
        - name: WORDPRESS_DB_NAME
          valueFrom:
           secretKeyRef:
             name: {{ .Values.secret.name }}
             key: db
        - name: WORDPRESS_DB_USER
          valueFrom:
           secretKeyRef:
             name: {{ .Values.secret.name }}
             key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: {{ .Values.secret.name }}
             key: password
        resources:
          limits:
            memory: {{ .Values.wordpress.resources.limits.memory }}
            cpu: {{ .Values.wordpress.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.service.port }}
