kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pvc
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
