apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
stringData:
  host: {{ .Values.db.host }}
  db: {{ .Values.db.name }}
  username: {{ .Values.db.user }}
  password: {{ .Values.db.password }}
