name: Terraform Deploy

on:
  push: {}

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          addons: ingress
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ">= 1.1.2"
        
      - name: Terraform init
        run: terraform init

      - name: Terraform deploy
        run: terraform apply --auto-approve

      - name: Terraform destroy
        run: terraform destroy --auto-approve
        continue-on-error: true
